import { Inter, Montserrat } from "next/font/google";
import React from "react";
import "./global.css";
import Link from "next/link";
import Image from "next/image";
import blurryShapes from "../assets/images/deco.jpg";
import Github from "../components/icons/Github";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
// If loading a variable font, you don't need to specify the font weight
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
  weight: ["700"],
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["400", "500", "600"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${montserrat.variable} ${inter.variable}`}>
      <body className="bg-slate-100">
        <nav className="sticky bg-slate-100 bg-opacity-90 saturate-150 top-0 left-0 backdrop-blur-md  w-full">
          <ul className="flex mx-auto max-w-lg">
            <li className="p-4">
              <a href="#home">Home</a>
            </li>
            <li className="p-4">
              <Link href="/docs">Docs</Link>
            </li>
            <li className="p-4">
              <Link href="/docs/roadmap">Roadmap</Link>
            </li>
            <li className="p-4 self-center">
              <a
                target="_blank"
                href="https://github.com/JulianKominovic/sittly-launcher"
                className="flex items-center"
              >
                <Github />
              </a>
            </li>
          </ul>
        </nav>
        <div className="bg-slate-100 bg-opacity-90">{children}</div>
        <Image
          loading="eager"
          priority={false}
          src={blurryShapes.src}
          alt=""
          aria-hidden
          width={1920}
          height={1080}
          className="h-screen object-cover opacity-60 w-full fixed top-0 left-0 -z-10"
        />
      </body>
    </html>
  );
}
